# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170921_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commments',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
